DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS ItemAuthor;


CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE Item (
    itemID INTEGER PRIMARY KEY AUTOINCREMENT,
    itemName TEXT NOT NULL,
    itemType TEXT CHECK (itemType IN ('books', 'periodicals', 'recordings', 'videos')) NOT NULL
);

CREATE TABLE Author (
    authorID INTEGER PRIMARY KEY AUTOINCREMENT,
    authorLastName TEXT NOT NULL,
    authorFirstName TEXT NOT NULL
);

CREATE TABLE ItemAuthor (
    itemID INTEGER NOT NULL,
    authorID INTEGER NOT NULL,
    PRIMARY KEY (itemID, authorID),
    FOREIGN KEY (itemID) REFERENCES Item (itemID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (authorID) REFERENCES Author (authorID) ON DELETE RESTRICT ON UPDATE CASCADE
);
